# Gavin lyons 06-2021
# Makefile to install library for ERM19264_UC1609_RPI library.
# URL: https://github.com/gavinlyonsrepo/ERM19264_UC1609_RPI
# Library is installed to /usr/lib and include files are placed at /usr/include.

# == Options ==
# 1. make = compile library
# 2. make install = install library to filesystem (may need sudo)
# 3. clean = deletes .o files generated by step 1 from build directory
# 4. make uninstall  = uninstalls library (may need sudo)
# =============

# Where you want it installed
PREFIX=/usr
# where to place the library
LIBDIR=$(PREFIX)/lib
# library name
LIB=libERM19264_UC1609_RPI
# shared library name
LIBNAME=$(LIB).so.1.0

MD=mkdir
SRC=src
OBJ=obj
SRCS = $(wildcard $(SRC)/*.cpp)
OBJS = $(patsubst $(SRC)%.cpp,  $(OBJ)/%.o, $(SRCS))

CXX=g++
CCFLAGS= -Ofast -mfpu=vfp -mfloat-abi=hard -march=armv6zk -mtune=arm1176jzf-s -Iinclude/
LDFLAGS= -lbcm2835

# make
all: clean pre-build ERM19264_UC1609_RPI

pre-build:
	@echo
	@echo "*****************"
	@echo "[START!]"
	@echo
	$(MD) -vp $(OBJ)


# Make the library
ERM19264_UC1609_RPI: $(OBJS)
	$(CXX) -shared -Wl,-soname,$(LIB).so.1 $(CCFLAGS) $(LDFLAGS)  -o ${LIBNAME} $^
	@echo "*****************"
	@echo "[DONE!]"

# Library parts
$(OBJ)/%.o: $(SRC)/%.cpp
	$(CXX) -Wall -fPIC -c $(CCFLAGS) $< -o $@

# Install the library to LIBPATH
install:
	@echo
	@echo "*****************"
	@echo "[INSTALL LIBRARY]"
	@if ( test ! -d $(PREFIX)/lib ) ; then mkdir -vp $(PREFIX)/lib ; fi
	@install -vm 0755 ${LIBNAME} ${LIBDIR}
	@ln -svf ${LIBDIR}/${LIBNAME} ${LIBDIR}/${LIB}.so.1
	@ln -svf ${LIBDIR}/${LIBNAME} ${LIBDIR}/${LIB}.so
	@ldconfig
	@rm -rvf ${LIB}.*
	@echo
	@echo "[INSTALL HEADERS]"
	@if ( test ! -d $(PREFIX)/include ) ; then mkdir -p $(PREFIX)/include ; fi
	@cp -vf  include/ERM19264_UC1609.hpp $(PREFIX)/include
	@cp -vf  include/ERM19264_UC1609_Print.hpp $(PREFIX)/include
	@cp -vf  include/ERM19264_graphics.hpp $(PREFIX)/include
	@cp -vf  include/ERM19264_font.hpp $(PREFIX)/include
	@cp -vf  include/ERM19264_gfxfont.hpp $(PREFIX)/include
	@echo "[DONE!]"

# Uninstall the library
uninstall:
	@echo "******************"
	@echo "[UNINSTALL LIBRARY]"
	@rm -vf ${LIBDIR}/${LIB}.*

	@echo "[UNINSTALL HEADERS]"
	@rm -rvf  $(PREFIX)/include/ERM19264_UC1609.hpp
	@rm -rvf  $(PREFIX)/include/ERM19264_UC1609_Print.hpp
	@rm -rvf  $(PREFIX)/include/ERM19264_graphics.hpp
	@rm -rvf  $(PREFIX)/include/ERM19264_font.hpp
	@rm -rvf  $(PREFIX)/include/ERM19264_gfxfont.hpp
	@echo "[DONE!]"

# clear build files
clean:
	@echo "******************"
	@echo "[CLEAN OBJECT FILES]"
	rm -rvf $(OBJ)/*.o ${LIB}.*
	@echo "[DONE!]"
